PREFIX math: <http://www.w3.org/2000/10/swap/math#>
PREFIX log: <http://www.w3.org/2000/10/swap/log#>
PREFIX : <https://eyereasoner.github.io/ns#>


CONSTRUCT {
    ?x a :odd2.
} WHERE {
    ?y a :odd.
    (?y 2) math:sum ?x.
} ;

